package pkg

import "crypto/ed25519"

// CertGen certificate the public key using master secret key by the CA
func CertGen(msk, pk []byte) []byte {
	return ed25519.Sign(msk, pk)
}

// CertVrfy verifies the certification of public key generated by the CA
func CertVrfy(cert, pk, mpk []byte) bool {
	return ed25519.Verify(mpk, pk, cert)
}