package pkg

import "crypto/ed25519"

type Certificate []byte

// CertGen certificate the public key using master secret key by the CA
func CertGen(msk, msg []byte) Certificate {
	return ed25519.Sign(msk, msg)
}

// CertVrfy verifies the certification of public key generated by the CA
func CertVrfy(cert Certificate, pk, mpk []byte) bool {
	return ed25519.Verify(mpk, pk, cert)
}

// Pair verifies that the public key is corresponding to the private key
func Pair(pk ed25519.PublicKey, sk ed25519.PrivateKey) bool {
	return pk.Equal(sk.Public())
}
